### ISSUE TITLE
Trying to use bundle causes an error

### ISSUE THREAD

**Issue by davidyell** [Jean-Beru/docker-swagger-cli#2]
Running this docker container now throws an error

```bash
❯ docker run --rm jeanberu/swagger-cli bundle --type yaml --outfile ./project/openapi/openapi-dist.yaml ./project/openapi/src/openapi.yaml
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module '/bundle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by davidyell** [comment]
This my own misunderstanding of Docker.

`docker run --rm jeanberu/swagger-cli swagger-cli bundle` ✅

**Comment by Jean-Beru** [comment]
No worries. Happy to see that this image is used by someone else than me :smile:
